# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

apiVersion: v2
name: guardrails-usvc
description: The Helm chart for deploying guardrails-usvc as microservice
type: application
version: 1.0.1
appVersion: "v1.0"

home: https://github.com/opea-project/GenAIComps

maintainers:
  - name: infracloudio
    url: https://github.com/infracloudio

sources:
  - https://github.com/opea-project/GenAIComps

dependencies:
  - name: opea-tgi
    version: 1.1.0
    repository: "file://../opea-tgi"
    alias: tgi
    condition: autodependency.enabled
