{{- if .Values.notebooks.pytorch.enabled }}
{{- include "kf-notebooks.checkNotebookCRD" . }}
apiVersion: kubeflow.org/v1
kind: Notebook
metadata:
  name: {{ include "kf-notebooks.fullname" . }}-{{ .Values.notebooks.pytorch.name }}
  labels:
    {{- include "kf-notebooks.labels" . | nindent 4 }}
    app: {{ .Values.notebooks.pytorch.name }}
spec:
  template:
    spec:
      containers:
      - name: {{ .Values.notebooks.pytorch.name }}
        image: "{{ .Values.notebooks.pytorch.image.repository }}:{{ .Values.notebooks.pytorch.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.notebooks.pytorch.image.pullPolicy }}
        resources:
          {{- toYaml .Values.notebooks.pytorch.resources | nindent 10 }}
        volumeMounts:
        - mountPath: /dev/shm
          name: dshm
        - mountPath: /home/jovyan
          name: workspace
      volumes:
      - emptyDir:
          medium: Memory
        name: dshm
      - name: workspace
        persistentVolumeClaim:
          claimName: {{ include "kf-notebooks.fullname" . }}-{{ .Values.notebooks.pytorch.name }}-workspace
{{- end }}
