{{- if .Values.notebooks.vscode.enabled }}
{{- include "kf-notebooks.checkNotebookCRD" . }}
apiVersion: kubeflow.org/v1
kind: Notebook
metadata:
  name: {{ printf "%s-%s" (include "kf-notebooks.fullname" .) .Values.notebooks.vscode.name | trunc 41 | trimSuffix "-" }}
  labels:
    {{- include "kf-notebooks.labels" . | nindent 4 }}
    app: {{ .Values.notebooks.vscode.name }}
spec:
  template:
    spec:
      containers:
      - name: {{ .Values.notebooks.vscode.name }}
        image: "{{ .Values.notebooks.vscode.image.repository }}:{{ .Values.notebooks.vscode.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.notebooks.vscode.image.pullPolicy }}
        resources:
          {{- toYaml .Values.notebooks.vscode.resources | nindent 10 }}
        volumeMounts:
        - mountPath: /dev/shm
          name: dshm
        - mountPath: /home/jovyan
          name: workspace
      volumes:
      - emptyDir:
          medium: Memory
        name: dshm
      - name: workspace
        persistentVolumeClaim:
          claimName: {{ include "kf-notebooks.notebooks.vscode.pvc.name" . }}
{{- end }}
